version: "3.3"

services:
  pg:
    image: postgres:13
    container_name: pg
    environment:
      - POSTGRES_PASSWORD=secret
    volumes:
      - ~/pg-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  barman:
    image: barman
    container_name: barman
    volumes:
      - ~/pg-data:/var/lib/postgresql/data
      - ~/barman-data:/var/lib/barman
